services:
  - type: web
    name: vnaturebot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: RENDER_URL
        fromService:
          name: vnaturebot
          type: web
          property: url